---
title: "AFM 423 - Group Project 2"
author: "Weixuan Xu 20568320"
date: "March 26, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
gc()
rm(list = ls())
```


```{r}

rm(list = ls())

library(ggplot2)
library(ISLR)
library(dplyr)
library(tidyr)
library(pander)
library(forcats)
library(DMwR)
library(ROSE)
library(caret)
library(tidyverse)
library(Hmisc)
library(MASS)
library(zoo)
library(data.table)


# 0. EDA (Aaron's Part)
#   0.0 Distribution of Results
#   0.1 Distribution of Variables


# Prep 0: Read CSV
train = data.frame(read.csv("training_cleaned.csv"))
train$VehicleAge = as.factor(train$VehicleAge)
train$IsBadBuy = as.factor(train$IsBadBuy)
train$Make = as.factor(train$Make)


# Prep 0.1: Remove Unwanted Col


#   Remove Empty Cols

train$Nationality = ifelse(train$Nationality == "AMERICAN", "AMERICAN", "OTHER")
train$Nationality = as.factor(train$Nationality)

train$AUCGUART = NULL
train$PRIMEUNIT = NULL
train$WheelTypeID = NULL
train$VNZIP1 = NULL
train$Trim = NULL
train$Color = NULL
train$VehYear = NULL
train$PurchDate = NULL
ID = train$RefId
train$RefId = NULL
train$IsOnlineSale = NULL
train$TopThreeAmericanName = NULL
train$Size = NULL
train$Transmission = NULL
train$SubModel = NULL
train$Model = NULL

ignore_make = c(
  "MAZDA",
  "MERCURY",
  "BUICK",
  "GMC",
  "HONDA",
  "OLDSMOBILE",
  "VOLKSWAGEN",
  "ISUZU",
  "SCION",
  "LINCOLN",
  "INFINITI",
  "VOLVO",
  "CADILLAC",
  "ACURA",
  "LEXUS",
  "SUBARU",
  "MINI",
  "PLYMOUTH",
  "HUMMER",
  "TOYOTA SCION"
)

train$Make = ifelse(train$Make %in% ignore_make, "OTHER", as.character(train$Make))

train$VehOdo = ifelse(as.numeric(train$VehOdo) < 73000, "<73000", ">=73000")

train$WheelType = ifelse(train$WheelType == "NULL", "Alloy", as.character(train$WheelType))

train$VehicleAge_group = ifelse(as.numeric(train$VehicleAge) < 5, "<5", ">=5")

train$VehicleAge = NULL

train$Make = as.factor(train$Make)
train$VehOdo = as.factor(train$VehOdo)
train$VehicleAge_group = as.factor(train$VehicleAge_group)
train$WheelType = as.factor(train$WheelType)

train$MMRAcquisitionAuctionAveragePrice = as.numeric(train$MMRAcquisitionAuctionAveragePrice)
train$MMRAcquisitionAuctionCleanPrice = as.numeric(train$MMRAcquisitionAuctionCleanPrice)
train$MMRAcquisitionRetailAveragePrice = as.numeric(train$MMRAcquisitionRetailAveragePrice)
train$MMRAcquisitonRetailCleanPrice = as.numeric(train$MMRAcquisitonRetailCleanPrice)

train$MMRCurrentAuctionAveragePrice = as.numeric(train$MMRCurrentAuctionAveragePrice)
train$MMRCurrentAuctionCleanPrice = as.numeric(train$MMRCurrentAuctionCleanPrice)
train$MMRCurrentRetailAveragePrice = as.numeric(train$MMRCurrentRetailAveragePrice)
train$MMRCurrentRetailCleanPrice = as.numeric(train$MMRCurrentRetailCleanPrice)

train$AvgPrice = (rowMeans(train[,10:17]))


# train$VehBCost = as.factor(train$VehBCost)
# train$WarrantyCost = as.factor(train$WarrantyCost)
train$BYRNO = as.factor(train$BYRNO)

train$MMRAcquisitionAuctionAveragePrice = NULL
train$MMRAcquisitionAuctionCleanPrice = NULL
train$MMRAcquisitionRetailAveragePrice = NULL
train$MMRAcquisitonRetailCleanPrice = NULL
train$MMRCurrentAuctionAveragePrice = NULL
train$MMRCurrentAuctionCleanPrice = NULL
train$MMRCurrentRetailAveragePrice = NULL
train$MMRCurrentRetailCleanPrice = NULL
train$PurchMonth = NULL
train$PurchYear = NULL
train$DoorCount = NULL
train$BYRNO = NULL



cols = seq(1:11)    
train[,cols] = apply(train[,cols], 2, function(x) as.numeric(as.factor(x)))
train$IsBadBuy = as.factor(train$IsBadBuy)



# PREP 1: Split
set.seed(42)
train_idx = createDataPartition(train$IsBadBuy, p = 0.70, list = FALSE)

trn = train[train_idx, ]
tst = train[-train_idx, ]

# Prep 2: SMOTE
trn_smote = SMOTE(IsBadBuy ~ ., data = trn, perc.over = 200)
tst_smote = SMOTE(IsBadBuy ~ ., data = tst, perc.over = 200)



# 2. Model Implementation
#   2.1 Logistic
cv_5 = trainControl(method = "cv", number = 5)

default_glm_mod = train(
  form = IsBadBuy ~ .,
  data = trn_smote,
  trControl = cv_5,
  method = "glm",
  family = "binomial"
)

accuracy = function(actual, predicted) {
  mean(actual == predicted)
}

accuracy(actual = tst_smote$IsBadBuy,
         predicted = predict(default_glm_mod, tst_smote))

#   2.2 KNN


#   2.3 LDA

default_lda_mod = lda(IsBadBuy ~ ., data = trn_smote)

accuracy(actual = tst_smote$IsBadBuy,
         predicted = predict(default_lda_mod, data = tst_smote))


#   2.4 QDA

default_qda_mod = qda(IsBadBuy ~ ., data = trn_smote)


#   2.5 ...More from Daniel


# 3. Model Comparison with Scores/Curves/Measures


# 4. Conclusion

# 5. Feedback
```
